services:
  db:
    image: postgres:16
    container_name: my_grocy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_grocy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_grocy_web
    environment:
      MIX_ENV: prod
      DB_HOST: db
      DATABASE_URL: ecto://postgres:postgres@db/my_grocy
      SECRET_KEY_BASE: aTyuJwGp3EWP5+7eRP9HK/FsnAXxpogHvhOQ2s6l4lLzohsc1JahRA24Atap9GsW
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: >
      sh -c "mix deps.get &&
             mix assets.deploy &&
             mix ecto.setup &&
             mix phx.server"

volumes:
  postgres_data:
